### ISSUE TITLE
How to use the program 

### ISSUE THREAD

**Issue by Sufferer000** [SMR76/adobe-connect-offline-player#1]
I downloaded and run it but no idea how to use it. It is written drop the session here but after tried to paste a recordings link nothing happened. Need instructions for dummies

**Comment by SMR76** [comment]
Thanks for using my app.
This is just a test version and does not work correctly if your presenter has been used as a file for the presentation.
Assume that the Adobe Connect ID is `xxxxxxxxxxx`. to export a recording into a zip file you can add `/output/xxxxxxxxxxx.zip?download=zip` at the end of the URL to download some zip archive containing a bunch of audio and video files as well as some .xml files. E.g., `https://my.adobeconnect.com/p6vwxp2d0c2e/output/xxxxxxxxxxx.zip?download=zip`
then you can use WinRAR(or anything to extract the zip file) and drag and drop indexstream.xml file or whole directory (the extracted folder) and watch that.
In the next version, I will try to make that easier (drag and drop zip file).

**Comment by 0smr** [comment]
> I downloaded and run it but no idea how to use it. It is written drop the session here but after tried to paste a recordings link nothing happened. Need instructions for dummies

Hi, thanks for using my app.
This is just a test version and does not work correctly if your presenter has been used a file for the presentation.
Assume that the Adobe Connect ID is `xxxxxxxxxxx`, to export a recording into a zip file you can add `/output/xxxxxxxxxxx.zip?download=zip` at the end of the URL to download some zip archive containing a bunch of audio and video files as well as some .xml files. E.g., `https://my.adobeconnect.com/p6vwxp2d0c2e/output/xxxxxxxxxxx.zip?download=zip`
then you can use WinRAR(or anything to extract the zip file) and drag and drop indexstream.xml file or whole directory (the extracted folder) and watch that.
In the next version, I will try to make that easier (drag and drop zip file).

**Comment by Sufferer000** [comment]
Hi, thanks for your work. About exporting a recording into a zip file, i believe that ADOBE just fixed that flaw and i think no more anyone can export recordings into zip files just by adding .zip thing. 

Unfortunately me and thousands of med students in my school depends on downloading class recordings i mean its like life and death situation for us because thanks to our school's magnificent IT department our online class management system is pretty much all the time Down. What i am trying to say is that please please develop something to download recordings, i swear i will buy it unless it costs more than 20 USD.

PS: This is a very time sensitive need because of incoming finals.

Thanks!

**Comment by rezaafsh** [comment]
> Hi, thanks for your work. About exporting a recording into a zip file, i believe that ADOBE just fixed that flaw and i think no more anyone can export recordings into zip files just by adding .zip thing.
> 
> Unfortunately me and thousands of med students in my school depends on downloading class recordings i mean its like life and death situation for us because thanks to our school's magnificent IT department our online class management system is pretty much all the time Down. What i am trying to say is that please please develop something to download recordings, i swear i will buy it unless it costs more than 20 USD.
> 
> PS: This is a very time sensitive need because of incoming finals.
> 
> Thanks!

At first sorry that we haven't good document for using that, we will add a `How to use application` in this branch as soon as possible.
Unfortunately due to Adobe connect issues and limits we have to stop developing this app, cause we couldn't find a good way to make that stable for the recorded meeting which has been used a file on them `pdf or etc` .
But be sure if we find something useful we will start developing that again.

**Comment by Sufferer000** [comment]
> > Hi, thanks for your work. About exporting a recording into a zip file, i believe that ADOBE just fixed that flaw and i think no more anyone can export recordings into zip files just by adding .zip thing.
> > Unfortunately me and thousands of med students in my school depends on downloading class recordings i mean its like life and death situation for us because thanks to our school's magnificent IT department our online class management system is pretty much all the time Down. What i am trying to say is that please please develop something to download recordings, i swear i will buy it unless it costs more than 20 USD.
> > PS: This is a very time sensitive need because of incoming finals.
> > Thanks!
> 
> At first sorry that we haven't good document for using that, we will add a `How to use application` in this branch as soon as possible.
> Unfortunately due to Adobe connect issues and limits we have to stop developing this app, cause we couldn't find a good way to make that stable for the recorded meeting which has been used a file on them `pdf or etc` .
> But be sure if we find something useful we will start developing that again.

Thank you for your work. Is there a way to download at least only the audio of recordings? Because being able to download even only the audio/sound of a recording would help enormously.

**Comment by rezaafsh** [comment]
> > > Hi, thanks for your work. About exporting a recording into a zip file, i believe that ADOBE just fixed that flaw and i think no more anyone can export recordings into zip files just by adding .zip thing.
> > > Unfortunately me and thousands of med students in my school depends on downloading class recordings i mean its like life and death situation for us because thanks to our school's magnificent IT department our online class management system is pretty much all the time Down. What i am trying to say is that please please develop something to download recordings, i swear i will buy it unless it costs more than 20 USD.
> > > PS: This is a very time sensitive need because of incoming finals.
> > > Thanks!
> > 
> > 
> > At first sorry that we haven't good document for using that, we will add a `How to use application` in this branch as soon as possible.
> > Unfortunately due to Adobe connect issues and limits we have to stop developing this app, cause we couldn't find a good way to make that stable for the recorded meeting which has been used a file on them `pdf or etc` .
> > But be sure if we find something useful we will start developing that again.
> 
> Thank you for your work. Is there a way to download at least only the audio of recordings? Because being able to download even only the audio/sound of a recording would help enormously.

Maybe your school's IT department limited access, but for being sure about that, follow this:
You follow that structure that we said above for download recorded meeting?
Can you send us a sample of your school recorded meeting link?
Please send a link which isn't private so we don't need username and password.
Best regards.

**Comment by Sufferer000** [comment]
> > > > Hi, thanks for your work. About exporting a recording into a zip file, i believe that ADOBE just fixed that flaw and i think no more anyone can export recordings into zip files just by adding .zip thing.
> > > > Unfortunately me and thousands of med students in my school depends on downloading class recordings i mean its like life and death situation for us because thanks to our school's magnificent IT department our online class management system is pretty much all the time Down. What i am trying to say is that please please develop something to download recordings, i swear i will buy it unless it costs more than 20 USD.
> > > > PS: This is a very time sensitive need because of incoming finals.
> > > > Thanks!
> > > 
> > > 
> > > At first sorry that we haven't good document for using that, we will add a `How to use application` in this branch as soon as possible.
> > > Unfortunately due to Adobe connect issues and limits we have to stop developing this app, cause we couldn't find a good way to make that stable for the recorded meeting which has been used a file on them `pdf or etc` .
> > > But be sure if we find something useful we will start developing that again.
> > 
> > 
> > Thank you for your work. Is there a way to download at least only the audio of recordings? Because being able to download even only the audio/sound of a recording would help enormously.
> 
> Maybe your school's IT department limited access, but for being sure about that, follow this:
> You follow that structure that we said above for download recorded meeting?
> Can you send us a sample of your school recorded meeting link?
> Please send a link which isn't private so we don't need username and password.
> Best regards.

I followed every step but adding .zip thing didn't work. Link is below. Please let me know if there is a problem with the link or need another one. 

https://sdutip.adobeconnect.com/_a3787855616/pzyjr5u6k20v/?session=em2breezphzi9wv6sq2gy9b6

Thank you.

**Comment by rezaafsh** [comment]
> > > > > Hi, thanks for your work. About exporting a recording into a zip file, i believe that ADOBE just fixed that flaw and i think no more anyone can export recordings into zip files just by adding .zip thing.
> > > > > Unfortunately me and thousands of med students in my school depends on downloading class recordings i mean its like life and death situation for us because thanks to our school's magnificent IT department our online class management system is pretty much all the time Down. What i am trying to say is that please please develop something to download recordings, i swear i will buy it unless it costs more than 20 USD.
> > > > > PS: This is a very time sensitive need because of incoming finals.
> > > > > Thanks!
> > > > 
> > > > 
> > > > At first sorry that we haven't good document for using that, we will add a `How to use application` in this branch as soon as possible.
> > > > Unfortunately due to Adobe connect issues and limits we have to stop developing this app, cause we couldn't find a good way to make that stable for the recorded meeting which has been used a file on them `pdf or etc` .
> > > > But be sure if we find something useful we will start developing that again.
> > > 
> > > 
> > > Thank you for your work. Is there a way to download at least only the audio of recordings? Because being able to download even only the audio/sound of a recording would help enormously.
> > 
> > 
> > Maybe your school's IT department limited access, but for being sure about that, follow this:
> > You follow that structure that we said above for download recorded meeting?
> > Can you send us a sample of your school recorded meeting link?
> > Please send a link which isn't private so we don't need username and password.
> > Best regards.
> 
> I followed every step but adding .zip thing didn't work. Link is below. Please let me know if there is a problem with the link or need another one.
> 
> https://sdutip.adobeconnect.com/_a3787855616/pzyjr5u6k20v/?session=em2breezphzi9wv6sq2gy9b6
> 
> Thank you.


So please test this link and let us know if that's worked. 
https://sdutip.adobeconnect.com/pzyjr5u6k20v/output/outputfile.zip?download=zip
And for good news we will start work again on that for work with pdf and etc.
King regards.

**Comment by Sufferer000** [comment]
I tested the link and it says i am not authorized to download. Thank you for starting to work again on this project. Me and other students here appreciate your work. I can not wait to hear more good news from you :-)

> > > > > > Hi, thanks for your work. About exporting a recording into a zip file, i believe that ADOBE just fixed that flaw and i think no more anyone can export recordings into zip files just by adding .zip thing.
> > > > > > Unfortunately me and thousands of med students in my school depends on downloading class recordings i mean its like life and death situation for us because thanks to our school's magnificent IT department our online class management system is pretty much all the time Down. What i am trying to say is that please please develop something to download recordings, i swear i will buy it unless it costs more than 20 USD.
> > > > > > PS: This is a very time sensitive need because of incoming finals.
> > > > > > Thanks!
> > > > > 
> > > > > 
> > > > > At first sorry that we haven't good document for using that, we will add a `How to use application` in this branch as soon as possible.
> > > > > Unfortunately due to Adobe connect issues and limits we have to stop developing this app, cause we couldn't find a good way to make that stable for the recorded meeting which has been used a file on them `pdf or etc` .
> > > > > But be sure if we find something useful we will start developing that again.
> > > > 
> > > > 
> > > > Thank you for your work. Is there a way to download at least only the audio of recordings? Because being able to download even only the audio/sound of a recording would help enormously.
> > > 
> > > 
> > > Maybe your school's IT department limited access, but for being sure about that, follow this:
> > > You follow that structure that we said above for download recorded meeting?
> > > Can you send us a sample of your school recorded meeting link?
> > > Please send a link which isn't private so we don't need username and password.
> > > Best regards.
> > 
> > 
> > I followed every step but adding .zip thing didn't work. Link is below. Please let me know if there is a problem with the link or need another one.
> > https://sdutip.adobeconnect.com/_a3787855616/pzyjr5u6k20v/?session=em2breezphzi9wv6sq2gy9b6
> > Thank you.
> 
> So please test this link and let us know if that's worked.
> https://sdutip.adobeconnect.com/pzyjr5u6k20v/output/outputfile.zip?download=zip
> And for good news we will start work again on that for work with pdf and etc.
> King regards.

I tested the link and it says i am not authorized to download. Thank you for starting to work again on this project. Me and other students here appreciate your work. I can not wait to hear more good news from you :-)

**Comment by rezaafsh** [comment]
> I tested the link and it says i am not authorized to download. Thank you for starting to work again on this project. Me and other students here appreciate your work. I can not wait to hear more good news from you :-)
> 
> > > > > > > Hi, thanks for your work. About exporting a recording into a zip file, i believe that ADOBE just fixed that flaw and i think no more anyone can export recordings into zip files just by adding .zip thing.
> > > > > > > Unfortunately me and thousands of med students in my school depends on downloading class recordings i mean its like life and death situation for us because thanks to our school's magnificent IT department our online class management system is pretty much all the time Down. What i am trying to say is that please please develop something to download recordings, i swear i will buy it unless it costs more than 20 USD.
> > > > > > > PS: This is a very time sensitive need because of incoming finals.
> > > > > > > Thanks!
> > > > > > 
> > > > > > 
> > > > > > At first sorry that we haven't good document for using that, we will add a `How to use application` in this branch as soon as possible.
> > > > > > Unfortunately due to Adobe connect issues and limits we have to stop developing this app, cause we couldn't find a good way to make that stable for the recorded meeting which has been used a file on them `pdf or etc` .
> > > > > > But be sure if we find something useful we will start developing that again.
> > > > > 
> > > > > 
> > > > > Thank you for your work. Is there a way to download at least only the audio of recordings? Because being able to download even only the audio/sound of a recording would help enormously.
> > > > 
> > > > 
> > > > Maybe your school's IT department limited access, but for being sure about that, follow this:
> > > > You follow that structure that we said above for download recorded meeting?
> > > > Can you send us a sample of your school recorded meeting link?
> > > > Please send a link which isn't private so we don't need username and password.
> > > > Best regards.
> > > 
> > > 
> > > I followed every step but adding .zip thing didn't work. Link is below. Please let me know if there is a problem with the link or need another one.
> > > https://sdutip.adobeconnect.com/_a3787855616/pzyjr5u6k20v/?session=em2breezphzi9wv6sq2gy9b6
> > > Thank you.
> > 
> > 
> > So please test this link and let us know if that's worked.
> > https://sdutip.adobeconnect.com/pzyjr5u6k20v/output/outputfile.zip?download=zip
> > And for good news we will start work again on that for work with pdf and etc.
> > King regards.
> 
> I tested the link and it says i am not authorized to download. Thank you for starting to work again on this project. Me and other students here appreciate your work. I can not wait to hear more good news from you :-)

Ok so that's limited by your college IT department.
If that's  possible, you and other student can ask them to give you access for downloading recorded meeting packages.
If they asked why, you can explain that there is a player that make you able to download and use that record's offline.
You can also give them our repository link to speak directly to us.
And your welcome, but even if every thing work, you need to download that package in first point.
So that's neccessary to have access for downloading that.
We will add auto download feature in next version, so that would be easy to give link and auto download packages.
King regards.
