### ISSUE TITLE
How to export Adobe Connect recording as a single mp4 or mkv files?

### ISSUE THREAD

**Issue by Goldoust** [SMR76/adobe-connect-offline-player#2]
Hi 
Its very nice work.
Is it possible to have a video output that includes all the comments, mouse movement, share screens and file sharing?

**Comment by 0smr** [comment]
Hi.
I'm so sorry, somehow I didn't notify this issue (I don't know why). 
No, this app is supposed to regenerate this mouse movement, user comments, and other stuff.
But because there is no one to use adobe connect anymore, I decided to archive this repository.
